networks:
  frontend:
  backend:

services:
  web:
    build: nginx
    ports:
      - "80:80"
    networks:
      - frontend
  webservice:
    build: .
    networks:
      - frontend
      - backend
    volumes:
      - "./config:/config"
      - "./TestAPI/src:/code"
